### PR TITLE
introduced `VRGFindOrFetchPackage`

### PR DESCRIPTION
**Pull request by evaleev**
`VRGFindOrFetchPackage` can simplify the task of composing `FindOrFetchXYZ` modules

### CODE REVIEW

**Comment by evaleev** [comment]
> This should also allow to specify a version (range) for the dependency

should be able to pass at the front of `FIND_PACKAGE_ARGS`

**Comment by Krzmbrzl** [comment]
Ah, true :+1:

**Comment by Krzmbrzl** [comment]
There is only a slight semantic issue with this approach in that `find_package` takes the version information as an unnamed argument and so the overall call looks like
```
    VRGFindOrFetchPackage(Catch2 "https://github.com/catchorg/Catch2.git" "${SEQUANT_TRACKED_CATCH2_TAG}"
            ADD_SUBDIR
            CONFIG_SUBDIR
            FIND_PACKAGE_ARGS 3
    )
```
where the `3` is somewhat meaningless from this context alone :thinking:

**Comment by evaleev** [comment]
In the most recent version `FIND_PACKAGE_ARGS` is only used for `find_package`: https://github.com/ValeevGroup/kit-cmake/pull/7/files#diff-716c5f00f3c4144ece3078047f53a820429caf59037785b49ca826bb4a7da919R36

**Comment by Krzmbrzl** [comment]
Yes, but you can't pass `VERSION 3` as `find_package` doesn't know a `VERSION` argument name. Instead, you can only pass the numeric version itself. See also https://cmake.org/cmake/help/latest/command/find_package.html

**Comment by evaleev** [comment]
> Yes, but you can't pass `VERSION 3` as `find_package` doesn't know a `VERSION` argument name. Instead, you can only pass the numeric version itself. See also https://cmake.org/cmake/help/latest/command/find_package.html

Ah yes ... I see, your complaint is about cosmetics ... well, I guess we could add another option but it might be safer to stick with the documented `find_package` signature

**Pull request merged**
